### ISSUE TITLE
gd-77 digital squelch

### ISSUE THREAD

**Issue by priceb4** [sergev/dmrconfig#15]
When programming the gd-77 all of the digital channels are configured to "tight" instead of "normal"  there is an option to specify for analog channels but not digital.

**Comment by sergev** [comment]
Does it make any difference for digital channels?
As far as I know, a concept of squelch level is not applicable to digital channels. Signal detection is performed based on synchronization to the digital frame structure, not on the signal level. That's why there is no Squelch column in the Digital channel table.

**Comment by sergev** [comment]
I'm afraid there is a bug in the Squelch value for GD-77. I need to double-check. First of all, it's numeric, and the comment should look like:
```
# 10) Squelch level: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
```

**Comment by sergev** [comment]
The bug has been fixed in ae9239bf22ecf580272c5dfdac80a2fd03fa5103.
Dmrconfig modified to print and set correct Normal/Tight values for analog channels. Normal value is used for digital channels.

**Comment by priceb4** [comment]
Thank you.  Tested and new settings work as expected.
