### ISSUE TITLE
Anytone 878 Unrecognized file size 7281175 bytes

### ISSUE THREAD

**Issue by jimallyn** [sergev/dmrconfig#36]
I downloaded the codeplug 878-PNW-Stock-CPS_v1.13-FW_v1.13_2019-07-07.rdt from the PNW DMR group.  Attempting to read the radio configuration from the codeplug returns:

Read codeplug from file '878-PNW-Stock-CPS_v1.13-FW_v1.13_2019-07-07.rdt'.
878-PNW-Stock-CPS_v1.13-FW_v1.13_2019-07-07.rdt: Unrecognized file size 7279679 bytes.

So I used the CPS to add a few local analog channels and load that into the radio, which worked fine.  Attempting to read the radio configuration from the modified codeplug returns:

Read codeplug from file 'Jims878_090519.rdt'.
Jims878_090519.rdt: Unrecognized file size 7281175 bytes.

**Comment by sergev** [comment]
Dmrconfig cannot read native Anytone codeplugs, sorry. The problem is that *.RDT files have a non-trivial proprietary format, not easy to reverse engineer. For that reason, dmrconfig uses it's own format for Anytone 868/878, basically a memory image. 

You can use dmrconfig to read a codeplug directly from your radio, then modify it and write it back.

**Comment by jimallyn** [comment]
Thanks, serge!
